version: "3.8"
services:

  auth-service:
    build: 
      context: ./backend/auth-service
      target: development
    container_name: shelfnow_auth
    ports:
      - "3001:3001"
    env_file:
      - ./backend/auth-service/.env
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./backend/auth-service:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev

  product-service:
    build: 
      context: ./backend/product-service
      target: development
    container_name: shelfnow_product
    ports:
      - "3002:3002"
    env_file:
      - ./backend/product-service/.env
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./backend/product-service:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev

  order-service:
    build: 
      context: ./backend/order-service
      target: development
    container_name: shelfnow_order
    ports:
      - "3003:3003"
    env_file:
      - ./backend/order-service/.env
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./backend/order-service:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev

  frontend:
    build:
      context: ./frontend
      target: development
    container_name: shelfnow_frontend
    ports:
      - "5173:5173"
    environment:
      - ./frontend/.env
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    depends_on:
      - auth-service
    command: npm run dev -- --host 0.0.0.0

  gateway:
    build: 
      context: ./backend/api-gateway
      target: development
    container_name: shelfnow_gateway
    ports:
      - "3000:3000"  # Gateway is the main entry point
    env_file:
      - ./backend/api-gateway/.env
    depends_on:
      - auth-service
      - product-service
      - order-service
    volumes:
      - ./backend/api-gateway:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    healthcheck:
      test: ["CMD", "node", "health-check.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mysql:
    image: mysql:8.0
    container_name: shelfnow_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shelfnow_auth_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      timeout: 30s
      retries: 10
      start_period: 40s

volumes:
  mysql_data: