version: "3.8"
services:
  auth-service:
    build: ./backend/auth-service
    container_name: shelfnow_auth
    ports:
      - "3001:3001"
    env_file:
      - ./backend/auth-service/.env
    depends_on:
      - mysql

  product-service:
    build: ./backend/product-service
    container_name: shelfnow_product
    ports:
      - "3002:3002"
    env_file:
      - ./backend/product-service/.env
    depends_on:
      - mysql

  order-service:
    build: ./backend/order-service
    container_name: shelfnow_order
    ports:
      - "3003:3003"
    env_file:
      - ./backend/order-service/.env
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shelfnow_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
